### ISSUE TITLE
Autocomplete disappears

### ISSUE THREAD

**Issue by svipas** [MhMadHamster/vscode-postcss-language#4] opened 2017-04-30 22:44 UTC
Hello,

if this plugin is enabled the autocomplete disappears, because the language mode is changed from CSS to PostCSS, I really like VS Code autocomplete, because it helps a lot, it will be very good to somehow fix this issue by having CSS language mode with coloring or PostCSS language mode, but with autocomplete.

**Comment by svipas** [comment] 2017-05-02 20:46
@MhMadHamster I'm wondering somehow it's possible to keep CSS language mode and have syntax coloring? Because this syntax coloring is really good, but when we enable PostCSS language mode these #3, #4 problems appears... In my opinion best option will be just enable CSS language mode and add all syntax coloring here which will fix these two issues above, but since I don't know if it's possible, I'm just wondering and asking.

**Comment by MhMadHamster** [comment] 2017-05-02 20:52
Thank you for feedback, honestly i dont have an idea right now, how to quickly fix this.
The problem is CSS intellisense as well as colorbox default behaviours for css/less/sass files and i didnt found yet, if there is a way(or if it even possible), to inherit it in custom language.
I'll probably contact devs, open issue or smth, anyway will update this as soon as i get response.

**Comment by svipas** [comment] 2017-05-02 20:55
@MhMadHamster Thank you very much. I think there's 2 options, but need to know which way is correct.

- Get syntax coloring for CSS language mode.
**OR**
- Get autocomplete, color box view for PostCSS language mode and again enable it by default.

**Comment by MhMadHamster** [comment] 2017-05-02 21:13
@svipben you can override existing colorizer, though it is did not seem to me as a good approach because you dont have some features in css which are supported by this plugin, so i'm looking forward for the second option i.e. somehow enabling CSS Intellisense and color box for PostCSS

**Comment by svipas** [comment] 2017-05-02 21:17
@MhMadHamster Good solution, I will be waiting for news, if you need any help, you can ask :+1:

**Comment by MhMadHamster** [comment] 2017-05-07 20:29
fixed in version 2.0

**Closed as completed by MhMadHamster** 2017-05-07 20:29 UTC

**Comment by svipas** [comment] 2017-05-08 13:34
@MhMadHamster So everything (autocomplete, color box) now works in this plugin? If yes, enable it by default for CSS files and it will be best plugin! I'm so happy! :smile:

**Comment by MhMadHamster** [comment] 2017-05-08 19:52
@svipben i dont think it is a good idea to turn on plugin for *.css files by default, because probably someone want to just try it out first and see how it works for his/her particular case, and then enable it for project which is using postcss or for whole workspace. In my opinion it is better to leave this dicision to user, for which files he wants to use plugin.
In addition, there is that issue with vscode-icons, which might seem confusing if you want to just write plain css, so i'll leave it as it is right now.

**Comment by svipas** [comment] 2017-05-09 16:17
@MhMadHamster Maybe you're right, it isn't hard to edit user settings to enable it by default. Thanks :+1:

**Comment by h-peters** [comment] 2017-07-17 06:45
@MhMadHamster Hi, i'm new to vscode and just installed your plugin. But IntelliSense seems not to be working or am i missing something? Are there some settings i need to configure? Thanks!

**Comment by MhMadHamster** [comment] 2017-07-17 09:46
Hi, what file extension are you using? by default, it should work for pcss and postcss, and in css, you would have default vs code IntelliSense. Have you installed other plugins that provide same functionality before?

**Comment by drprasad-capillary** [comment] 2018-12-27 12:53
@MhMadHamster Same problem for me also. auto complete not working. i didn't install any other plugins related to css
